### ISSUE TITLE
Почему ua, а не uk?

### ISSUE THREAD

**Issue by HIKC50** [LastCraftInc/localization#16]
Почему ua, а не uk?
Это наверное издавна решили что
uk - это язык
UA - страна
Предлагаю переименовать файл `ua.yml` на `uk.yml`.

**Comment by ghost** [comment]
Uk - United Kingdom, умник

**Comment by HIKC50** [comment]
как ты можешь объяснить то, что префикс в украинской Википедии (Minecraft Wiki) `uk`, а не `ua`, умник?!
https://uk.wikipedia.org/wiki/Головна_сторінка
https://minecraft-uk.gamepedia.com/Головна_сторінка

**Comment by HIKC50** [comment]
даже на [рус. википедии](https://ru.wikipedia.org/wiki/ISO_639) ISO 639-1 пишет **uk**.

**Comment by ShredRum** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/27852427/59136473-03947b00-898c-11e9-832d-dd2a801115ca.png)
Хм...

**Comment by HIKC50** [comment]
Ну так что?
